import{a as L,S as b,i as c}from"./assets/vendor--6n4cVRZ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const w=L.create({baseURL:"https://pixabay.com/api/",params:{key:"54667939-2958d96aa870b71b0c19ccb5c",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function v(r,o=1){return(await w.get("",{params:{q:r,page:o,per_page:15}})).data}const l=document.querySelector(".gallery"),u=document.querySelector(".loader"),d=document.querySelector(".load-more"),q=new b(".gallery a",{captionDelay:250,captionsData:"alt"});function S(r){const o=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:t,views:n,comments:g,downloads:h})=>`<li class="gallery-item">
        <a href = "${s}" class="gallery-link">
        <img src = "${a}" alt = "${e}" class="gallery-image" /></a>
        <div class="info" >
        <p>Likes: ${t}</p>
        <p>Views: ${n}</p>
        <p>Comments: ${g}</p>
        <p>Downloads: ${h}</p>
        </div>
        </li>`).join("");l.insertAdjacentHTML("beforeend",o),q.refresh()}function M(){l.innerHTML=""}function f(){u.classList.add("is-visible")}function P(){u.classList.remove("is-visible")}function $(){d.classList.add("is-hidden")}function m(){d.classList.remove("is-hidden")}const B=document.querySelector(".form"),x=document.querySelector(".load-more");let p="",i=1,O=15;x.addEventListener("click",async()=>{i+=1,f(),await y()});B.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(!o){c.warning({message:"Please enter a search query!",position:"topRight"});return}p=o,i=1,M(),f(),m(),await y()});async function y(){try{const r=await v(p,i);if(!r.hits.length&&i===1){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}if(S(r.hits),i>1){const a=document.querySelector(".gallery").firstElementChild;if(a){const{height:s}=a.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}const o=Math.ceil(r.totalHits/O);i<o?m():($(),c.info({message:"We're sorry, but you've reached the end of search results."}))}catch{c.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{P()}}
//# sourceMappingURL=index.js.map
