import{a as b,S as w,i as c}from"./assets/vendor--6n4cVRZ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const v=b.create({baseURL:"https://pixabay.com/api/",params:{key:"54667939-2958d96aa870b71b0c19ccb5c",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function q(r,o=1){return(await v.get("",{params:{q:r,page:o,per_page:15}})).data}const d=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),S=new w(".gallery a",{captionDelay:250,captionsData:"alt"});function M(r){const o=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:t,views:n,comments:h,downloads:L})=>`<li class="gallery-item">
        <a href = "${i}" class="gallery-link">
        <img src = "${a}" alt = "${e}" class="gallery-image" /></a>
        <div class="info" >
        <p>Likes: ${t}</p>
        <p>Views: ${n}</p>
        <p>Comments: ${h}</p>
        <p>Downloads: ${L}</p>
        </div>
        </li>`).join("");d.insertAdjacentHTML("beforeend",o),S.refresh()}function P(){d.innerHTML=""}function p(){f.classList.add("is-visible")}function u(){f.classList.remove("is-visible")}function l(){m.classList.add("is-hidden")}function $(){m.classList.remove("is-hidden")}const B=document.querySelector(".form"),x=document.querySelector(".load-more");let y="",s=1,O=15;x.addEventListener("click",async()=>{s+=1,p(),l(),await g()});B.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(!o){c.warning({message:"Please enter a search query!",position:"topRight"});return}y=o,s=1,P(),p(),l(),await g()});async function g(){try{const r=await q(y,s);if(!r.hits.length&&s===1){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l(),u();return}M(r.hits);const o=Math.ceil(r.totalHits/O);if(s>1){const a=document.querySelector(".gallery").firstElementChild;if(a){const{height:i}=a.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}s<o?$():(l(),s!==1&&c.info({message:"We're sorry, but you've reached the end of search results."}))}catch{c.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{u()}}
//# sourceMappingURL=index.js.map
